# -*- coding: utf-8 -*-
"""rotate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hH0uDCSmoFBoNu_ZNdhN5gTdi3a6kY9x
"""

# install tesseract
!sudo apt-get install tesseract-ocr
!pip install pytesseract

# import the necessary packages
from pytesseract import Output
import pytesseract as pt
import argparse
import imutils
import cv2

def get_argument_parser():
    '''Parse the command-line arguments for this program.'''

    parser = argparse.ArgumentParser()

    parser.add_argument("-i", "--image", required=True,
                        help="path to input image to be OCR'd")

    return parser

######################################################################

# rotate the image to correct the orientation
def rotate(options):
  args = vars(options)

  # load the input image, convert it from BGR to RGB channel ordering,
  # and use Tesseract to determine the text orientation
  image = cv2.imread(args["image"])

  results = pt.image_to_osd(image, output_type=Output.DICT)

  # rotate the image to correct the orientation
  rotated = imutils.rotate_bound(image, angle=results["rotate"])

  cv2.imwrite(args["image"], rotated)

def main():
    '''Parse args and call notescan_main().'''
    rotate(options=get_argument_parser().parse_args())

if __name__ == '__main__':
    main()